### ISSUE TITLE
Workflow broken, setup-nuget failure

### ISSUE THREAD

**Issue by rannes** [agoda-com/net-loadbalancing#53]
# Why?
```
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: latest
```
This step seems to be broken, as other MR's are getting blocked by it

# What?
Make it deployable again
